# This is the dependabot configuration file that automates dependency updates
# Updates section configures how dependabot should handle dependency updates:
# - Monitors GitHub Actions workflow dependencies in the root directory
# - Checks for updates weekly
#
# Learn more at https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#configuration-options-for-the-dependabotyml-file